### ISSUE TITLE
For the preprocessing

### ISSUE THREAD

**Issue by cecilia930426** [burchim/EfficientConformer#1]
Is there any preprocessing scripts for the data? 
`FileNotFoundError: [Errno 2] No such file or directory: 'datasets/LibriSpeech/train-other-500/6741/253270/6741-253270-0020.flac_len'` 
It seems I need to deal with the data before putting to the model.

**Comment by burchim** [comment]
Yes, data preprocessing is necessary for your first experiment.
Use the '--prepare_dataset' flag to preprocess the dataset. This will tokenize text sequences and save data lengths.
You can also use the '--create_tokenizer' flag to create and train a new sentencepiece tokenizer.
`python main.py --config_file configs/config_file.json --create_tokenizer --prepare_dataset`
