### ISSUE TITLE
ngram models

### ISSUE THREAD

**Issue by shaojinding** [burchim/EfficientConformer#11]
Hi,

Thanks for the awesome works! I was trying to evaluate my trained models with a ngram LM. However, it seems to be very tricky to get a ngram works with bpe. Could you please share a ngram model (e.g., the one specified at callbacks/ngram/6gram_256.arpa), or give me some pointers on how to train it myself?

Thanks,
Shaojin

**Comment by burchim** [comment]
Hi,

Sorry for the delay!
I added the missing 6-gram to the shared folders.
You should be able to access it [here](https://drive.google.com/drive/folders/1ZhevurjySBT_WMD6Q79g86XUJnTQ8VPa).

The ngram was trained using NeMo toolkit's ngram script: 
[https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html)

The trick is to tokenize the training corpus using the corresponding bpe tokenizer and then to replace each token by a special character to create a new corpus. This new corpus can be used to train a bpe n-gram: 
[https://github.com/NVIDIA/NeMo/blob/stable/scripts/asr_language_modeling/ngram_lm/train_kenlm.py](https://github.com/NVIDIA/NeMo/blob/stable/scripts/asr_language_modeling/ngram_lm/train_kenlm.py)

Best,
Maxime

**Comment by kafan1986** [comment]
@burchim I have trained the n-gram model with the above script. Can I directly use it with the beam search decoding method or do some other changes are required?

**Comment by burchim** [comment]
Hi,

If you trained the n-gram using the same text tokenizer as your model, yes the script should work.

However, if the tokenizers used for the model and n-gram are different, the decoding will not be done correctly.
