### ISSUE TITLE
Can this architecture support streaming ASR?

### ISSUE THREAD

**Issue by kafan1986** [burchim/EfficientConformer#12]
Hello @burchim 

What all changes are required to support streaming inference?

**Comment by harisgulzar1** [comment]
@kafan1986 did you mean if CTC decoder supports the streaming ASR?
I have been working with the Conformer-CTC decoder and want to ask if it is possible to do streaming ASR with CTC decoder?

**Comment by burchim** [comment]
Hi @harisgulzar1,

Streaming ASR is possible using CTC. There is currently no implementation of a streaming decoding function but this is absolutely possible !

Decoding can be performed chunk by chunk using the CTC encoder in convolution manner with a given context size and step size of audio frames given as hyper-parameters.

It is also possible to decode a streaming audio frame by frame with a model trained with causal context (masked future context in attention and convolutions). But this would require small changes in the implementation and configs. For now, all given configs train full context models.

**Comment by harisgulzar1** [comment]
Hi @burchim 
Thanks for your comment.
That clarifies my doubt, I will try to implement it and see how it goes.

**Comment by debasish-mihup** [comment]
@harisgulzar1 did you get the time to implement and test the streaming ASR? How is the performance?

**Comment by debasish-mihup** [comment]
@harisgulzar1 I did take a look into this. I have some doubts, are they only maintaining the context and using it during the decoder part of the pipeline or they are using context during the encoder phase as well?

**Comment by harisgulzar1** [comment]
I have implemented the inference code based on the above google collaboratory example. But the accuracy is very poor for small iterative chunks of audio.
I think for streaming application, we need to retrain the models with zero future context, by setting the [causal paramter](https://github.com/burchim/EfficientConformer/blob/master/models/encoders.py#L94) to True in the [ecoder.py](https://github.com/burchim/EfficientConformer/blob/master/models/encoders.py#L94) file.
Is my intuition correct about it?

**Comment by kafan1986** [comment]
@harisgulzar1 Did you get it to work reliably in streaming mode?
