### ISSUE TITLE
Link to Pretrained Original-Conformer Models

### ISSUE THREAD

**Issue by harisgulzar1** [burchim/EfficientConformer#16]
Thanks for the amazing work.
I want to test the original CTC-Conformer with this code.
If you have placed the pre-trained models on GD, can you please share the link like you have shared the links to Efficient Conformer model on Colab page. Thanks

**Comment by burchim** [comment]
Hi,

I no longer have access to the pre-trained checkpoints of other experiments. However, you should be able to recover the paper results using the ConformerCTCSmall.json config if you have access to 4 RTX 2080 GPUs !

**Comment by harisgulzar1** [comment]
All right, thanks. I will try to reproduce the results.
