### ISSUE TITLE
The Google Drive Link for Pretrained Model no more works

### ISSUE THREAD

**Issue by harisgulzar1** [burchim/EfficientConformer#18]
The pre-trained models for Efficient COnformer CTC are no more accessible by Google drive link.
I personally have the models saved, but I just wanted to point it out for future reference for those who want to try the code.

**Comment by burchim** [comment]
Hi

If you are having troubles with downloading the checkpoints using gdown. Updating gdown with `pip install --upgrade --no-cache-dir gdown` should fix the problem.

**Comment by harisgulzar1** [comment]
The issue was solved using this solution. Thanks.
