### ISSUE TITLE
Possible to decouple the encoder and decoder training

### ISSUE THREAD

**Issue by kafan1986** [burchim/EfficientConformer#19]
As per my understanding, current ASR training pipeline train the encoder and decoder separately as encoder training doesn't require transcript, so huge amount of data can be used to make the encoder generalize better and decoder is trained and fine tunned separately at a later stage. Is my understanding correct?

If so, can the relevant changes be made in the current repo, to allow to train the two separately?

**Comment by burchim** [comment]
Hi, I think you are referring to self-supervised pre-training of the encoder using [Wav2Vec](https://arxiv.org/abs/2006.11477) or [HuBERT](https://arxiv.org/abs/2106.07447) techniques to acquire more general audio knowledge without requiring transcripts. We did not use self-supervised learning techniques in this work as they require some more hardware resources but trained our model directly using the LibriSpeech dataset transcripts.

However, one could imagine doing a research work combing our model architecture with these techniques. Of course some changes would need to be made in the repo to support self-supervised pre-training objectives but this would be possible.
