### ISSUE TITLE
How to run inference using existing models?

### ISSUE THREAD

**Issue by youssefavx** [burchim/EfficientConformer#2]
Hey, I see a method of evaluation on the readme, but is there some example code for running inference on an example file?

**Comment by burchim** [comment]
The repo now includes a demo notebook showing how to load pretrained models and run inference on individual files :)
-> [Demo Notebook](https://colab.research.google.com/github/burchim/EfficientConformer/blob/master/EfficientConformer.ipynb)

**Comment by youssefavx** [comment]
@burchim !! You even put it in a colab notebook! Thank you so much!

**Comment by youssefavx** [comment]
@burchim I tried to run the small model on Colab on one of my files and got this error for some reason when running this code:

```
audiofile = '/content/drive/MyDrive/test.wav'
audio, sr = torchaudio.load(audiofile)

# Predict sentence
prediction = model.gready_search_decoding(audio.to(device), x_len=torch.tensor([len(audio[0])], device=device))[0]
print("model prediction:", prediction, '\n')
```

```
IndexError                                Traceback (most recent call last)
<ipython-input-16-750b6f475cbd> in <module>()
      5 
      6 # Predict sentence
----> 7 prediction = model.gready_search_decoding(audio.to(device), x_len=torch.tensor([len(audio[0])], device=device))
      8 print("model prediction:", prediction, '\n')

/content/EfficientConformer/models/model_ctc.py in gready_search_decoding(self, x, x_len)
    112 
    113             # Decoding Loop
--> 114             for t in range(logits_len[b]):
    115 
    116                 # Blank Prediction

IndexError: index 1 is out of bounds for dimension 0 with size 1
```

I assume this is just me doing something stupid with the code.

**Comment by youssefavx** [comment]
I also just tried converting my file to .flac, 16kHz, and placing it in a folder like the Librispeech example so that I don't make many changes to the code. I only deleted the displaying the audio bit, and I still got that error.

**Comment by burchim** [comment]
I think that the error comes from the fact that your audio file has multiple audio channels.
This will result in a tensor of size (channels, audio_length) instead of (1, audio_length). 
`prediction = model.gready_search_decoding(audio.to(device), x_len=torch.tensor(audio.size(0)*[audio.size(1)], device=device))`
This should resolve the problem by transcribing each channel separately.

**Comment by youssefavx** [comment]
Ah! Silly me. If I'd only checked the difference between my file and the librispeech ones. Thank you so much again for being so helpful. I will try again.

**Comment by youssefavx** [comment]
Just an update: I tried it and it worked! Thanks again.
