### ISSUE TITLE
Could you share your id of the  "LibriSpeech_bpe_1000.model"

### ISSUE THREAD

**Issue by ZhengWenrui** [burchim/EfficientConformer#22]
Hello, i find the id of the "LibriSpeech_bpe_256.model", but i want to download the "LibriSpeech_bpe_1000.model" for the training of Transducer, can you tell me the id of the "LibriSpeech_bpe_1000.model"? Thank you very much!

**Comment by ZhengWenrui** [comment]
Thanks, i may know how to train a BPE model. If i can use the "create_tokenizer" function in the "preprocessing.py" to create a BPE model?

**Comment by ZhengWenrui** [comment]
Thanks, i may know how to create a BPE model. Ii can use "--create_tokenizer" to create a BPE model!

**Comment by burchim** [comment]
Hi, I do not possess the exact 1000 bpe tokenizer anymore but yes you can simply use the "--create_tokenizer" flag to automatically train a tokenizer for the Transducer model.

**Comment by ZhengWenrui** [comment]
Thank you very much!
