### ISSUE TITLE
Questions about variational noise.

### ISSUE THREAD

**Issue by maxwellzh** [burchim/EfficientConformer#3]
Hi Maxime @burchim , thanks for the released codes. I recently look into your implementation of RNN-Transducer and Conformer and have these questions:

1. You apply the variational noise after training 20k steps. Is there any reference about this manner? Or is it a tuned setting according to your experiments?
2. Is the broadcast of variational noise across all processes needed for distributed data parallel training?

Thanks!
Huahuan.

**Comment by burchim** [comment]
Hi,

1. We followed previous works by applying variational noise on decoder weights after a number of training steps for regularization. Noise parameters were taken from the [Lingvo toolkit](https://github.com/tensorflow/lingvo/blob/master/lingvo/tasks/asr/params/librispeech.py). The final clean WER will be 0.1% to 0.2% worse if you remove it from the config.
2. We didn't experiment to remove the broadcast, but feel free to remove it if you have any issues :)

**Comment by maxwellzh** [comment]
Thank you for the details!
