### ISSUE TITLE
LM model required when beam size greater than 1?

### ISSUE THREAD

**Issue by debasish-mihup** [burchim/EfficientConformer#6]
When I tried running your inference script in non gready mode (beam size greater than 1), it was giving me error for not having my LM model present. Is it a compulsory requirement?

**Comment by debasish-mihup** [comment]
Made the ticket in error. LM is not required for beam size > 1

**Comment by burchim** [comment]
Hi,

Yes, the model will try to load the n-gram language model during beam search but this repo does not include it.
You simply need to set the [ngram_path](https://github.com/burchim/EfficientConformer/blob/2f59ed2564c45c5978742fe1984cd48363064c88/configs/EfficientConformerCTCSmall.json#L90) param to null in the config.
Please refer to this [link](https://docs.nvidia.com/deeplearning/nemo/user-guide/docs/en/main/asr/asr_language_modeling.html) if you wish to train your own n-gram LM.
