### ISSUE TITLE
Demo Notebook - failing 

### ISSUE THREAD

**Issue by TzurV** [burchim/EfficientConformer#8]
failing while running the original notebook in 

```
import json
import glob
import torch
import torchaudio
import IPython.display as ipd
from functions import create_model
import matplotlib.pyplot as plt

```

    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-10-1e4ca53c14dc> in <module>()
          4 import torchaudio
          5 import IPython.display as ipd
    ----> 6 from functions import create_model
          7 import matplotlib.pyplot as plt
    
    4 frames
    /usr/local/lib/python3.7/dist-packages/warp_rnnt/__init__.py in <module>()
          1 import torch
    ----> 2 import warp_rnnt._C as core
          3 from typing import Optional, AnyStr
          4 from pkg_resources import get_distribution
          5 
    
    ImportError: /usr/local/lib/python3.7/dist-packages/warp_rnnt/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor8data_ptrIfEEPT_v
    
    ---------------------------------------------------------------------------
    NOTE: If your import is failing due to a missing package, you can
    manually install dependencies using either !pip or !apt.
    
    To view examples of installing some common dependencies, click the
    "Open Examples" button below.
    ---------------------------------------------------------------------------

**Comment by burchim** [comment]
Hi

Thanks for pointing it out!
Torchaudio 0.10.0 requires PyTorch 1.10.0 and the warp_rnnt library does not seem to support it.
Setting torchaudio to torchaudio==0.9.0 in the requirements.txt file should fix the issue.

**Comment by debasish-mihup** [comment]
@burchim @TzurV I have been able to work with Pytorch 1.10.0 perfectly. Uninstall the pip version and build the warp_rnnt from source.
